#!/bin/sh
#
# @name Gazebo x500 mono cam
#
# @type Quadrotor
#

PX4_SIM_MODEL=${PX4_SIM_MODEL:=x500_mono_cam_down}

. ${R}etc/init.d-posix/airframes/4001_gz_x500

# GCS connection loss failsafe mode is disabled
param set-default NAV_DLL_ACT 0
